### PR TITLE
fix sse encoder

### PR DESCRIPTION
**Pull request by aqrit**
#PR15 was broken

test that proves this PR to be correct:
https://gist.github.com/aqrit/6ac040c9ac0542c5b92b89c9b7f3bad0

### CODE REVIEW

**Comment by lemire** [comment]
Ping: @KWillets

**Comment by KWillets** [comment]
Our tests must have failed before -- can we add this to our validation?

**Comment by lemire** [comment]
@KWillets  if you approve/recommend the merge, I am willing to do the legwork of turning the manual test into a unit test.

Of course, it would be nicer if @aqrit added a unit test of his own, but it is no big deal.

**Comment by lemire** [comment]
Added unit test so that this should no longer occur.

**Pull request merged**
