### PR TITLE
minor optimizations for the sse encoder

### PR DESCRIPTION
**Pull request by aqrit**
Better instruction selection.
Sorry if this is annoying :-(

### CODE REVIEW

**Comment by KWillets** [comment]
Not at all, this looks fun.  I'll review this weekend.

**Comment by lemire** [comment]
(This looks amazing.)

**Comment by aqrit** [comment]
sse doesn't seem to help much for plain encoding
```
      memcpy:    4416397
improved sse:    6519862
  scalar bsr:    7039434
 current sse:    7387148
```

https://gist.github.com/aqrit/406ae9b67e89ec6bbc5ca162c3a5689a

**Comment by lemire** [comment]
What do you call plain encoding?

**Comment by aqrit** [comment]
scalar code using Bit Scan Reverse

**Comment by KWillets** [comment]
ARM has a nice SIMD BSR/CLZ; that's one thing that SSE is missing.

**Pull request merged**
