### PR TITLE
Fixes and verifies issue 42

### PR DESCRIPTION
**Pull request by lemire**
We decoding, our functions may read up to 16 extra bytes from the input (beyond the actual compressed data). Thus the users of this library, for safety, should ensure that there is allocated data 16 bytes beyond the compressed data.

### CODE REVIEW

**Comment by fzhedu** [comment]
@lemire I think we should pad 32 bytes for AVX as the vector lane of AVX is up to 256bits.
streamvbyte

**Comment by lemire** [comment]
@fzhedu We only read into 16-byte registers (so not 32 bytes). However, there may yet still be a bug. Can you share the input that was used to produce this case so we can examine it and produce a fix?

**Comment by lemire** [comment]
I do refer you to documentation, this bit is important...

> During decoding, the library may read up to `STREAMVBYTE_PADDING` extra bytes
 from the input buffer (these bytes are read but never used).

This requirement could be removed.

**Comment by fzhedu** [comment]
> @fzhedu We only read into 16-byte registers (so not 32 bytes). However, there may yet still be a bug. Can you share the input that was used to produce this case so we can examine it and produce a fix?

ok, I will recheck and test again.

**Pull request merged**
